<?php

/**
 * @file
 * Notify module sends e-mail digests of new content and comments.
 *
 * The notification module allows users to subscribe to periodic e-mails which
 * include all new or revised content and/or comments much like the daily news
 * letters sent by some websites.  Even if this feature is not configured for
 * normal site users, it can be a useful feature for an administrator of a site
 * to monitor content submissions and comment posts.
 */

define('NOTIFY_NODE_TYPE', 'notify_node_type_');

/**
 * Implements hook_help().
 */
function notify_help($section) {
  switch ($section) {
    case 'admin/help#notify':
      $output = '<p>' . t('The notification module allows users to subscribe to periodic e-mails which include all new or revised content and/or comments much like the daily news letters sent by some websites.  Even if this feature is not configured for normal site users, it can be a useful feature for an administrator of a site to monitor content submissions and comment posts.') . '</p>';
      $output .= '<p>' . t('The administrator sets the frequency of the e-mails in the notify administration interface. They can also set how many e-mail failures should occur before notify stops sending notifications.  Note that cron must be enabled for notifications to be sent out.') . '</p>';
      $output .= '<p>'  . t('You can:</p><ul><li>set up your site to run tasks automatically at required intervals. For more information, see <a href="@cron">cron</a>.', array('@cron' => url('admin/config/system/cron'))) . '</li>';
      $output .= '<li>' . t('administer <a href="@notify">notify settings', array('@notify' => url('admin/config/people/notify'))) . '</a>.</li>';
      $output .= '<li>' . t('administer <a href="@notifu">notify users and batch operations', array('@notifu' => url('admin/config/people/notify/users'))) . '</a>.</li>';
      $output .= '<p>'  . t('For more information please read the community documentation handbook <a href="@notifyhb">Notify page</a>.', array('@notifyhb' => 'http://www.drupal.org/handbook/modules/notify/')) . '</p>';
      return $output;
  }
}

/**
 * Submit for the notify_admin_settings form.
 */
function notify_admin_settings_submit($form, &$form_state) {
  variable_set('notify_send', $form_state['values']['notify_send']);
  variable_set('notify_send_hour', $form_state['values']['notify_send_hour']);
  variable_set('notify_attempts', $form_state['values']['notify_attempts']);
  variable_set('notify_include_updates', $form_state['values']['notify_include_updates']);
  variable_set('notify_reg_default', $form_state['values']['notify_reg_default']);
  foreach (node_type_get_types() as $type => $object) {
    $ntype = 'notify_node_type_' . $type;
    variable_set($ntype, $form_state['values'][$ntype]);
  }
  $last  = variable_get('notify_send_last', 0);
  _notify_next_notificaton($last, TRUE);
  drupal_set_message(t('Notify admin settings saved.'));
}


/**
 * Menu callback, show admin notification settings form.
 */
function notify_admin_settings($form, &$form_state) {
  $period = array(
    60 => format_interval(60),
    120 => format_interval(120),
    180 => format_interval(180),
    300 => format_interval(300),
    600 => format_interval(600),
    900 => format_interval(900),
    1800 => format_interval(1800),
    3600 => format_interval(3600),
    10800 => format_interval(10800),
    21600 => format_interval(21600),
    32400 => format_interval(32400),
    43200 => format_interval(43200),
    86400 => format_interval(86400),
    172800 => format_interval(172800),
    259200 => format_interval(259200),
    604800 => format_interval(604800),
    1209600 => format_interval(1209600),
    2419200 => format_interval(2419200),
    -1 => t('Never'),
  );

  $form = array();

  $form['notify_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('E-mail notification settings'),
    '#collapsible' => TRUE,
  );

  $form['notify_settings']['notify_send'] = array(
    '#type' => 'select',
    '#title' => t('Send notifications every'),
    '#default_value' => variable_get('notify_send', array(86400)),
    '#options' => $period,
    '#description' => t('How often should new content notifications be sent? Requires cron to be running at least this often.'),
  );

  $form['notify_settings']['notify_send_hour'] = array(
    '#type' => 'select',
    '#title' => t('Hour to Send Notifications'),
    '#description' => t('Specify the hour (24-hour clock) in which notifications should be sent, if the frequency is one day or greater.'),
    '#default_value' => variable_get('notify_send_hour', 9),
    '#options' => array(
      0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
      10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
      20, 21, 22, 23,
    ),
  );

  $form['notify_settings']['notify_attempts'] = array(
    '#type' => 'select',
    '#title' => t('Number of failed sends after which notifications are disabled'),
    '#default_value' => variable_get('notify_attempts', array(5)),
    '#options' => array(t('Disabled'), 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 20),
  );

  $form['notify_settings']['notify_include_updates'] = array(
    '#type' => 'checkbox',
    '#title' => t('Include updated posts in notifications'),
    '#return_value' => 1,
    '#default_value' => variable_get('notify_include_updates', 1),
  );

  /*
  TODO;
  $form['notify_settings']['notify_unpublished'] = array(
    '#type' => 'checkbox',
    '#title' => t('Administrator to be notified about unpublished'),
    '#return_value' => 1,
    '#default_value' => variable_get('notify_unpublished', 1),
  );
  */

  $set = 'defaults';
  $form['notify_defaults'] = array(
    '#type' => 'fieldset',
    '#title' => t('Notification default for new users'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#description' => t('The default master switch for new users (check for enabled, uncheck for disabled).'),
  );

  $form['notify_defaults']['notify_reg_default'] = array(
    '#type' => 'checkbox',
    '#title' => t('Receive e-mail notifications'),
    '#return_value' => 1,
    '#default_value' => variable_get('notify_reg_default', 1),
  );

  $set = 'ntype';
  $form[$set] = array(
    '#type' => 'fieldset',
    '#title' => t('Notification by node type'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#description' => t('Having nothing checked defaults to sending notifications about all node types.'),
  );

  foreach (node_type_get_types() as $type => $object) {
    $form[$set][NOTIFY_NODE_TYPE . $type] = array(
      '#type' => 'checkbox',
      '#title' => $object->name,
      '#return_value' => 1,
      '#default_value' => variable_get(NOTIFY_NODE_TYPE . $type, 0),
    );
  }

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save settings'),
  );

  //return system_settings_form($form);
  return ($form);
}

/**
 * Helper function to count nodes and comments queued for notification
 *
 * @return array
 *   nodes comments
 */
function _notify_count_nodes() {
  $now = REQUEST_TIME;
  $period = variable_get('notify_send_last', $now - variable_get('notify_send', 86400));

  // Fetch all node type authorized by notify settings.
  $ntype = array();
  foreach (node_type_get_types() as $type => $name) {
    if (variable_get(NOTIFY_NODE_TYPE . $type, 0)) {
      $ntype[] = $type;
    }
  }

  // Build query to fetch desired nodes.
  $q = db_select('node', 'n');
  $q->fields('n', array('nid'));
  $q->condition('status', NODE_PUBLISHED);
  if (count($ntype) >= 1) {
    $q->condition('n.type', $ntype, 'IN');
  }
  if (variable_get('notify_include_updates', 1)) {
    $q->condition(db_or()->condition(db_and()->condition('n.created', $period, '>')->condition('n.created', $now, '<='))
                         ->condition(db_and()->condition('n.changed', $period, '>')->condition('n.changed', $now, '<=')));
  }
  else {
    $q->condition('n.created', $period, '>');
    $q->condition('n.created', $now, '<=');
  }
  $q->orderBy('n.created', 'asc');
  $result = $q->execute();
  $nodes = $result->rowCount();

  // Fetch new published comments.
  $comments = array();
  if (module_exists('comment')) {
    $q = db_select('comment', 'c');
    $q->join('node', 'n', 'c.nid = n.nid');
    $q->leftJoin('notify_unpublished_comments_queue', 'q', 'q.cid = c.cid');
    $q->fields('c');
    $q->condition('c.status', COMMENT_PUBLISHED, '=');
    $q->condition('q.cid', '', 'IS NULL');
    if (count($ntype) >= 1) {
      $q->condition('n.type', $ntype, 'IN');
    }
    if (variable_get('notify_include_updates', 1)) {
      $q->condition(db_or()->condition(db_and()->condition('c.created', $period, '>')->condition('c.created', $now, '<='))
                           ->condition(db_and()->condition('c.changed', $period, '>')->condition('c.changed', $now, '<=')));
    }
    else {
      $q->condition('c.created', $period, '>');
      $q->condition('c.created', $now, '<=');
    }
    $q->orderBy('c.nid', 'asc');
    $q->orderBy('c.changed', 'asc');
    $cresult = $q->execute();
    $comments = $cresult->rowCount();

    // Add any comments that are now published but still in the queue.
    $result = db_query("SELECT 1
      FROM {comment} c
      INNER JOIN {notify_unpublished_comments_queue} q ON q.cid = c.cid
      WHERE c.status = :status", array(':status' => COMMENT_PUBLISHED));

    $comments += $result->rowCount();
  }

  return array($nodes, $comments);
}






/**
 * Compute the next time a notification should be sent.
 * 
 * @param int $send_last
 *   timestamp of last notification
 *
 * @return int
 *   -1 never, 0 send instantly, else next time to notify.
 */
function _notify_next_notificaton($send_last, $reset=0) {
  $send_interval = variable_get('notify_send', 86400);
  if ($send_interval < 0) {
    return(-1);
  }
  $next_last = $next_frst = $send_last + $send_interval;
  $next = variable_get('notify_send_next', 0);
  if (REQUEST_TIME >= $next_frst) {
    return(0);
  }
  // dpm($next);
  if (!$next || $reset) {
    $send_hour  = variable_get('notify_send_hour',  0);


    if ($send_interval >= 86400) {
      $next_last = strtotime(date('Y-m-d ', $next_frst) . $send_hour . ':00:00');
      if ($next_last < REQUEST_TIME) $next_last += 86400;
    }
    variable_set('notify_send_next', $next_last);
    return($next_last);
  }
  return($next);
}


/**
 * Implements hook_cron().
 */
function notify_cron() {
  $now = REQUEST_TIME;
  $last  = variable_get('notify_send_last', 0);
  $next = _notify_next_notificaton($last);
  if ($now > $next) {
    _notify_send($now);
  }
}

/**
 * Implements hook_user_cancel().
 */
function notify_user_cancel($edit, $account, $method) {
  global $user;
  db_delete('notify')
  ->condition('uid', $user->uid)
  ->execute();
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function notify_form_user_register_form_alter(&$form, &$form_state, $form_id) {
  $form += _notify_user_reg_fields();
}

/**
 * Implements hook_user_insert().
 */
function notify_user_insert(&$edit, $account, $category) {
  if (isset($edit['notify_decision']) && $edit['notify_decision'] == 1) {
    db_insert('notify')
      ->fields(array(
      'uid' => $account->uid,
      'status' => 1,
      'node' => 1,
      'teasers' => 0,
      'comment' => 0,
    ))
      ->execute();
    $edit['notify_decision'] = NULL;
  }
}

/**
 * Returns form fields to be added to User Regsitration form.
 */
function _notify_user_reg_fields() {
  if (!user_access('access notify')) {
    return array();
  }

  // Get the variable for how often the notifications are sent out.
  $period = variable_get("notify_send", 86400);

  // Add a fieldset containing a checkbox for users to accept
  // getting updates on the registration form.
  $fields['notify_agree'] = array(
    '#type' => 'fieldset',
    '#title' => t('E-mail Notifications'),
  );

  // Add the checkbox to the fieldset.
  $fields['notify_agree']['notify_decision'] = array(
    '#type' => 'checkbox',
    '#title' => t('Receive e-mail notifications of new content posted to this site. Notifications are sent every @interval.', array('@interval' => format_interval($period))),
    '#return_value' => 1,
    '#default_value' => variable_get('notify_reg_default', 1),
  );

  return $fields;
}


/**
 * Implements hook_permission().
 */
function notify_permission() {
  return array(
    'access notify' => array(
      'title' => t('access notify'),
      'description' => t('Allow user to setup and receive notifications when there is new content'),
    ),
    'administer notify' => array(
      'title' => t('administer notify'),
      'description' => t('Administer the notify module'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function notify_menu() {
  $items = array();

  $items['admin/config/people/notify'] = array(
    'title' => 'Notification settings',
    'description' => 'Adjust settings for new content notifications sent by e-mail.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('notify_admin_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer notify'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/people/notify/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/config/people/notify/users'] = array(
    'title' => 'Users',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('notify_admin_users'),
    'access callback' => 'user_access',
    'access arguments' => array('administer notify'),
    'type' => MENU_LOCAL_TASK,
    'weight' => -9,
  );
  $items['user/%user/notify'] = array(
    'title' => 'Notification settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('notify_user_settings_form', 1),
    'access callback' => 'notify_user_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Checks access to notifications settings tab.
 */
function notify_user_access($account = NULL) {
  return $account->uid &&
    (
      // Always let users view their own profile.
      ($GLOBALS['user']->uid == $account->uid && user_access('access notify'))  ||
      // Administrators can view all accounts.
      user_access('administer notify')
    );
}


/**
 * Register the form data theme into a table at admin/user/user/notify.
 *
 * @return array
 *   form data theme.
 */
function notify_theme() {
  return array(
    'notify_admin_users' => array(
      'render element' => 'form',
    ),
  );
}


/**
 * Menu callback; show user notification options.
 */
function notify_user_settings_form($form, &$form_state, $arg) {
  global $user;

  if ($user->uid != $arg->uid && !user_access('administer notify')) {
    drupal_access_denied();
    return;
  }

  $account = user_load($arg->uid);
  if (!is_object($account)) {
    drupal_not_found();
    return;
  }

  $result = db_query('SELECT u.uid, u.name, u.mail, n.status, n.node, n.teasers, n.comment FROM {users} u LEFT JOIN {notify} n ON u.uid = n.uid WHERE u.uid = :uid AND u.status = :status', array(':uid' => $account->uid, ':status' => 1));
  $notify = $result->fetchObject();

  $form = array();
  if (!$notify->mail) {
    drupal_set_message(t('Your e-mail address must be specified on your <a href="@url">my account</a> page.', array('@url' => url('user/' . $account->uid . '/edit'))), 'error');
  }

  $form['notify_page_master'] = array(
    '#type' => 'fieldset',
    '#title' => t('Master switch'),
  );
  // If user existed before notify was enabled, these are not set in db.
  if (!isset($notify->status)) {
    $notify->status = 0;
    $notify->node = 0;
    $notify->teasers = 0;
    $notify->comment = 0;
  }
  $form['notify_page_master']['status'] = array(
    '#type' => 'radios',
    '#title' => t('Notify status'),
    '#default_value' => $notify->status,
    '#options' => array(t('Disabled'), t('Enabled')),
    '#description' => t('The master switch overrides all other settings for Notify.  You can use it to suspend notifications without having to disturb any of your options under &#8220;Detailed setting&#8221;.'),
  );

  $form['notify_page_detailed'] = array(
    '#type' => 'fieldset',
    '#title' => t('Detailed settings'),
  );
  $form['notify_page_detailed']['node'] = array(
    '#type' => 'radios',
    '#title' => t('Notify new content'),
    '#default_value' => $notify->node,
    '#options' => array(t('Disabled'), t('Enabled')),
    '#description' => t('Include new posts in the notification mail.'),
  );
  $form['notify_page_detailed']['teasers'] = array(
    '#type' => 'radios',
    '#title' => t('Content'),
    '#default_value' => $notify->teasers,
    '#options' => array(
      t('Title only'),
      t('Title + Teaser'),
      t('Title + Body'),
      t('Title + Body + Fields'),
    ),
    '#description' => t('Select the amount of each post that you would like to see in your notification e-mails.'),
  );
  $form['notify_page_detailed']['comment'] = array(
    '#type' => 'radios',
    '#title' => t('Notify new comments'),
    '#default_value' => $notify->comment,
    '#options' => array(t('Disabled'), t('Enabled')),
    '#description' => t('Include new comments in the notification mail.'),
  );
  $form['uid'] = array(
    '#type' => 'value',
    '#value' => $account->uid,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save settings'),
  );

  return $form;
}

/**
 * Submit for the notify_user_settings form.
 */
function notify_user_settings_form_submit($form, &$form_state) {
  unset($form);
  db_delete('notify')
    ->condition('uid', $form_state['values']['uid'])
    ->execute();

  $id = db_insert('notify')
    ->fields(array(
    'uid' => $form_state['values']['uid'],
    'status' => $form_state['values']['status'],
    'node' => $form_state['values']['node'],
    'teasers' => $form_state['values']['teasers'],
    'comment' => $form_state['values']['comment'],
  ))
    ->execute();
  drupal_set_message(t('Notify settings saved.'));
}

/**
 * Menu callback, show admin list of user notification settings.
 */
function notify_admin_users($form, &$form_state) {
  $send_last  = variable_get('notify_send_last', 0);
  $next_last = _notify_next_notificaton($send_last);
  $sent = variable_get('notify_num_sent', 0);
  if ($sent == 0) {
    $sent = t('No e-mails were sent');
  }
  elseif ($sent > 0) {
    $sent = t('sent ') . format_plural($sent, '1 e-mail', '@count e-mails');
  }
  else {
    $sent = -$sent;
    $sent = t('sending ') . format_plural($sent, '1 e-mail', '@count e-mails') . t(' failed');
  }

  $last = $send_last ? format_date($send_last, 'short') : t('never.');

  if ($next_last == -1) {
    $batch_msg = t('No more notifications scheduled');
  } elseif ($next_last == 0) {
    $batch_msg = t('the next notification is scheduled for the next cron run');
  }
  else {
    $next = format_date($next_last, 'short');
    $batch_msg = t('The next notification is scheduled for the first cron run after ') . $next;
  }
  $schedule = t('Last notification ran ') . $last . ' (' . $sent . '). ' . $batch_msg . '.';

  $form = array();

  $form['#tree'] = TRUE;
  $form['info'] = array('#value' => t('The following table shows all users that have notifications enabled.'));

  $form['users'] = array();

  // Fetch users with notify enabled.
  $q = db_select('notify', 'n');
  $q->join('users', 'u', 'n.uid = u.uid');
  $q->fields('u', array('uid', 'name', 'mail', 'language'));
  $q->fields('n', array('status', 'node', 'comment', 'attempts', 'teasers'));
  $q->condition('n.status', 1);
  $q->condition('u.status', 1);
  $q->orderBy('u.name');
  $uresult = $q->execute();

  foreach ($uresult as $user) {
    $form['users'][$user->uid] = array();
    $form['users'][$user->uid]['name'] = array(
      '#markup' => theme('username', array('account' => $user)),
    );
    $form['users'][$user->uid]['mail'] = array(
      '#markup' => $user->mail,
    );
    $form['users'][$user->uid]['node'] = array(
      '#type' => 'checkbox',
      '#default_value' => $user->node,
    );
    $form['users'][$user->uid]['teasers'] = array(
      '#type' => 'select',
      '#default_value' => $user->teasers,
      '#options' => array(
        t('Title only'),
        t('Title + Teaser'),
        t('Title + Body'),
        t('Title + Body + Fields'),
      ),
    );
    $form['users'][$user->uid]['comment'] = array(
      '#type' => 'checkbox',
      '#default_value' => $user->comment,
    );
    $form['users'][$user->uid]['attempts'] = array(
      '#type' => 'textfield',
      '#size' => 2,
      '#default_value' => $user->attempts ? intval($user->attempts) : 0,
    );
  }

  $form['flush'] = array(
    '#title' => t('Flush e-mail queue'),
    '#type' => 'checkbox',
    '#default_value' => FALSE,
    '#description' => t('Check to send out any pending notification e-mails currently in queue.'),
  );

  /*
  TODO
  $form['bulk'] = array(
    '#title' => t('Batch subscribe all users'),
    '#type' => 'checkbox',
    '#default_value' => FALSE,
    '#description' => t('Set the master switch for all users to enabled.'),
  );
  */

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save settings / Execute'),
  );

  $form['batch'] = array(
    '#type' => 'fieldset',
    '#title' => t('Status'),
    '#collapsible' => TRUE,
  );

  list ($c_node, $c_comm) = _notify_count_nodes();
  $s_node = format_plural($c_node, '1 node', '@count nodes');
  $s_comm = format_plural($c_comm, '1 comment', '@count comments');

  // $db_next = variable_get('notify_send_next', -13); if ($db_next > 0) $db_next = format_date($db_next, 'short'); // DB

  $form['batch']['schedule'] = array(
    '#markup' => $schedule . '<br/>' . t('Queued for next notificantion are ') . $s_node . ', and ' . $s_comm. '.',
  );

  return $form;
}

/**
 * Submit for the notify_admin_users form.
 */
function notify_admin_users_submit($form, &$form_state) {
  unset($form);

  if (!array_key_exists('users', $form_state['values'])) {
    drupal_set_message('No users have notifications enabled.', 'error');
    return;
  }
  if ($form_state['values']['users']) {
    foreach ($form_state['values']['users'] as $uid => $settings) {
      db_update('notify')
      ->fields(array(
        'node' => $settings['node'],
        'teasers' => $settings['teasers'],
        'comment' => $settings['comment'],
        'attempts' => $settings['attempts'],
      ))
      ->condition('uid', $uid)
      ->execute();
    }
  }
  drupal_set_message(t('Notify settings saved / batch executed.'));

  if ($form_state['values']['flush']) {
    $send_start = REQUEST_TIME;
    list($num_sent, $num_failed) = _notify_send($send_start);

    if ($num_sent > 0) {
      drupal_set_message(t('!count pending notification e-mails have been sent.', array('!count' => $num_sent)));
      variable_set('notify_num_sent', $num_sent);
    }
    elseif ($num_failed > 0) {
      drupal_set_message(t('!count notification e-mails could not be sent.', array('!count' => $num_failed)), 'error');
      variable_set('notify_num_sent', 0-$num_sent);
    }
    else {
      drupal_set_message(t('No notification e-mails needed to be sent.'));
      variable_set('notify_num_sent', 0);
    }
  }

/*
  if ($form_state['values']['bulk']) {
    drupal_set_message(t('Batch subscribe is planned for a future release, but not implemented yet.'));
  }
*/
}

/**
 * Theme function to theme the admin user settings form in a table format.
 */
function theme_notify_admin_users($variables) {
  $form = $variables['form'];
  $output = drupal_render($form['info']);
  $header = array(
    t('Username'),
    t('E-mail address'),
    t('Content'),
    t('Teasers'),
    t('Comment'),
    t('Failed attempts'),
  );

  $rows = array();
  foreach (element_children($form['users']) as $uid) {
    $row = array();
    foreach (element_children($form['users'][$uid]) as $entry_key) {
      unset($form['users'][$uid][$entry_key]['#title']);

      $row[] = drupal_render($form['users'][$uid][$entry_key]);
    }
    $rows[] = $row;
  }

  if (!$rows) {
    $rows[] = array(array(
        'data' => t('No users have notifications enabled.'),
        'colspan' => 6,
      ));
  }
  $output .= theme('table', array('header' => $header, 'rows' => $rows));

  $output .= drupal_render_children($form);
  return $output;
}

/**
 * Formatting of outgoing mail, taken from mail.inc, part of project.module.
 */
function _notify_content($node, $notify) {
  $txt = '';

  switch ($notify->teasers) {
    case 0:
      return $txt;

    case 1:
      $content = node_view($node, 'teaser');
      if (isset($content['body'][0]['#markup'])) {
        $txt = $content['body'][0]['#markup'];
      }
      break;

    case 2:
      $content = node_view($node, 'full');
      if (isset($content['body'][0]['#markup'])) {
        $txt = $content['body'][0]['#markup'];
      }
      break;

    case 3:
      $content = node_view($node, 'full');
      // Run of all children so that every attacked field is also included.
      $children = element_children($content, TRUE);

      foreach ($children as $child) {
        if (isset($content[$child]['#title']) && isset($content[$child][0]['#markup'])) {
          $txt .= $content[$child]['#title'] . ': ';
          $txt .= $content[$child][0]['#markup'] . "\n\n";
        }
      }
  }

  return drupal_html_to_text($txt);
}

/**
 * Helper function to send the notification e-mail.
 *
 * TODO: Needs some cleanup and themability.
 */
function _notify_send($send_start = NULL) {
  $send_start = $send_start ? $send_start : REQUEST_TIME;
  $period = variable_get('notify_send_last', $send_start - variable_get('notify_send', 86400));
  $separator = '------------------------------------------------------------------------------';
  $mini_separator = '---';

  $num_sent = 0;
  $num_failed = 0;

  // Store current user.
  _notify_switch_user();

  // Fetch all node type authorized by notify settings.
  $ntype = array();
  foreach (node_type_get_types() as $type => $name) {
    if (variable_get(NOTIFY_NODE_TYPE . $type, 0)) {
      $ntype[] = $type;
    }
  }

  // Build query to fetch desired nodes.
  $q = db_select('node', 'n');
  $q->fields('n', array('nid'));
  $q->condition('status', NODE_PUBLISHED);
  if (count($ntype) >= 1) {
    $q->condition('n.type', $ntype, 'IN');
  }
  if (variable_get('notify_include_updates', 1)) {
    $q->condition(db_or()->condition(db_and()->condition('n.created', $period, '>')->condition('n.created', $send_start, '<='))
                         ->condition(db_and()->condition('n.changed', $period, '>')->condition('n.changed', $send_start, '<=')));
  }
  else {
    $q->condition('n.created', $period, '>');
    $q->condition('n.created', $send_start, '<=');
  }
  $q->orderBy('n.created', 'asc');
  $result = $q->execute();
  $c_nodes = $result->rowCount();

  // Run the query, and load the nodes.
  // Query as if user 1, we check for individual user access later.
  _notify_switch_user(1);
  $nodes = array();
  foreach ($result as $node) {
    $nodes[$node->nid] = node_load($node->nid);
  }

  // Fetch new published comments.
  $comments = array();
  if (module_exists('comment')) {
    _notify_queue_unpublished_comments();

    $q = db_select('comment', 'c');
    $q->join('node', 'n', 'c.nid = n.nid');
    $q->leftJoin('notify_unpublished_comments_queue', 'q', 'q.cid = c.cid');
    $q->fields('c');
    $q->condition('c.status', COMMENT_PUBLISHED, '=');
    $q->condition('q.cid', '', 'IS NULL');
    if (count($ntype) >= 1) {
      $q->condition('n.type', $ntype, 'IN');
    }
    if (variable_get('notify_include_updates', 1)) {
      $q->condition(db_or()->condition(db_and()->condition('c.created', $period, '>')->condition('c.created', $send_start, '<='))
                           ->condition(db_and()->condition('c.changed', $period, '>')->condition('c.changed', $send_start, '<=')));
    }
    else {
      $q->condition('c.created', $period, '>');
      $q->condition('c.created', $send_start, '<=');
    }
    $q->orderBy('c.nid', 'asc');
    $q->orderBy('c.changed', 'asc');
    $cresult = $q->execute();

    foreach ($cresult as $comment) {
      $comments[$comment->nid][] = $comment;
    }

    // Add any comments that have been published since they were added to the queue.
    $result = db_query("SELECT c.*
      FROM {comment} c
      INNER JOIN {notify_unpublished_comments_queue} q ON q.cid = c.cid
      WHERE c.status = :status", array(':status' => COMMENT_PUBLISHED));

    foreach ($result as $comment) {
      $comments[$comment->nid][] = $comment;
    }

    db_query("DELETE q
      FROM {notify_unpublished_comments_queue} q
      INNER JOIN {comment} c ON c.cid = q.cid
      WHERE c.status = :status", array(':status' => COMMENT_PUBLISHED));
  }

  if (count($nodes) || count($comments)) {

    // Fetch users with notify enabled.
    $q = db_select('notify', 'n');
    $q->join('users', 'u', 'n.uid = u.uid');
    $q->fields('u', array('uid', 'name', 'mail', 'language'));
    $q->fields('n', array('status', 'node', 'teasers', 'comment'));
    $q->condition('n.status', 1);
    $q->condition('u.status', 1);
    $q->condition('n.attempts', variable_get('notify_attempts', 5), '<=');
    $uresult = $q->execute();

    foreach ($uresult as $user) {
      // Switch current user to this account to use node_access functions, etc.
      _notify_switch_user($user->uid);

      $node_body = '';
      $comment_body = '';

      // Write new node content to e-mail if user has permissions and nodes are
      // ready to be sent. @TODO - cache by role.
      if ($user->node && user_access('access content') && count($nodes)) {

        $node_count = 0;
        foreach ($nodes as $node) {
          // Skip to next if this user is NOT allowed to view this node.
          if (!node_access('view', $node)) {
            continue;
          }

          $node_revs_list = node_revision_list($node);
          $nrl_vals = array_values($node_revs_list);
          $vers = array_shift($nrl_vals);

          // @TODO: Add functionality to hook into moderation modules?
          if ($node->status == 1) {
            $status = t('Published');
            if (count($node_revs_list) > 1) {
              $edit_status = t('last edited');
            }
          }
          elseif ($node->status == 0) {
            $status = t('Unpublished');
            if (count($node_revs_list) > 1) {
              $edit_status = t('last edited');
            }
          }

          if ($node_count > 0) {
            $node_body .= $mini_separator . "\n\n";
          }
          $node_body .= ++$node_count . '. ' . $node->title . "\n";
          if (count($node_revs_list) > 1) {
            $node_body .= t('!type was !edit_status by !author.', array(
              '!type' => node_type_get_name($node),
              '!edit_status' => $edit_status,
              '!author' => ($vers->name ? $vers->name : variable_get('anonymous', 'Anonymous')),
            )) . "\r\n";
          }
          $node_body .= t('!status !type by !author', array(
            '!status' => $status,
            '!type' => node_type_get_name($node),
            '!author' => ($node->name ? $node->name : variable_get('anonymous', 'Anonymous')),
          )) . "\n";
          $node_body .= '[ ' . url('node/' . $node->nid, array(
            'absolute' => TRUE,
          )) . " ]\n\n";
          $node_body .= _notify_content($node, $user) . "\n";
        }

        // Prepend node e-mail header as long as user could access at
        // least one node.
        if ($node_count > 0) {
          $node_body = $separator . "\n" . t('Recent content - !count', array(
            '!count' => format_plural(count($nodes), '1 new post', '@count new posts'),
          )) . "\n" . $separator . "\n\n" . $node_body;
        }
      }

      // Write new comments to e-mail if user has permissions and there are
      // comments to be sent.
      if ($user->comment && user_access('access comments') && count($comments)) {
        $total_comment_count = 0;
        foreach ($comments as $nid => $comment) {
          // If we don't already have the node, fetch it.
          if (!isset($nodes[$nid])) {
            $node = node_load($nid);
          }
          else {
            $node = $nodes[$nid];
          }

          // Don't show comments if we're not allowed to view this node.
          if (!node_access('view', $node)) {
            continue;
          }

          if ($comment_body) {
            $comment_body .= $mini_separator . "\n\n";
          }
          $comment_body .= t('!count attached to !type posted by !author: !title', array(
            '!count' => format_plural(count($comment), '1 new comment', '@count new comments'),
            '!title' => $node->title,
            '!type'  => node_type_get_name($node),
            '!author' => $node->name ? $node->name : variable_get('anonymous', 'Anonymous'),
          )) . "\n";

          $comment_count = 0;
          foreach ($comment as $c) {
            // Determine whether to show comment status.
            if (user_access('administer comments')) {
              $status = $c->status == COMMENT_PUBLISHED ? t('Published') : t('Unpublished');
              $status = " [$status]";
            }
            $comment_body .= '   ' . ++$comment_count . '.' . t('!status !title by !author', array(
              '!status' => $status, '!title' => $c->subject, '!author' => ($c->name ? $c->name : variable_get('anonymous', 'Anonymous')),
            )) . "\n"
              . '     ' . url('node/' . $nid, array('fragment' => 'comment-' . $c->cid, 'absolute' => TRUE)) . "\n\n";

            /* @TODO - some people may not want comment body in the e-mail, so make it an option instead of always included */
            $comment_loaded = comment_load($c->cid);
            if (isset($comment_loaded->comment_body[$comment_loaded->language][0]['value'])) {
              $format = $comment_loaded->comment_body[$comment_loaded->language][0]['format'];
              $comment_body .= drupal_html_to_text(check_markup($comment_loaded->comment_body[$comment_loaded->language][0]['value'], $format, $comment_loaded->language, FALSE)) . "\n\n";
            }
            $total_comment_count++;
          }
        }

        if ($total_comment_count > 0) {
          $comment_body = $separator . "\n" . t('Recent comments - !count', array(
            '!count' => format_plural($total_comment_count, '1 new comment', '@count new comments'),
          )) . "\n" . $separator . "\n\n" . $comment_body;
        }
      }

      $body = $node_body . $comment_body;

      // If there was anything new, send mail.
      if ($body) {
        // Set up initial values for e-mail.
        $headers = array();
        // 'From' => "$from_name <$from>");
        if (!drupal_mail('notify', 'send', $user->mail, user_preferred_language($user), array('content' => $body))) {
          $num_failed++;
          db_update('notify')
          ->expression('attempts', 'attempts + 1')
          ->condition('uid', $user->uid)
          ->execute();
          watchdog('notify', 'User %name (%mail) could not be notified. Mail error.', array('%name' => $user->name, '%mail' => $user->mail), WATCHDOG_ERROR);
        }
        else {
          $num_sent++;
          watchdog('notify', 'User %name (%mail) notified successfully.', array('%name' => $user->name, '%mail' => $user->mail), WATCHDOG_INFO);
        }
      }
    }
  }
  variable_set('notify_send_last', $send_start);
  variable_set('notify_send_next', 0);
  _notify_switch_user();   // Restore user.
  return array($num_sent, $num_failed);
}

/**
 * Implements hook_mail().
 */
function notify_mail($key, &$message, $params) {
  global $user;

  $message['headers']['MIME-Version'] = '1.0';
  $message['headers']['Content-Type'] = 'text/plain;charset=utf-8';
  $message['subject'] = t('!sitename new content notification for !username', array(
    '!username' => $user->name,
    '!sitename' => variable_get('site_name', 'Drupal'),
  ));
  $message['body'][] = t('Greetings !user,', array('!user' => $user->name)) . "\n\n";
  $message['body'][] = $params['content'];
  $message['body'][] = "\n-- \n";
  $message['body'][] = t('This is an automatic e-mail from !sitename.',
    array('!sitename' => variable_get('site_name', 'Drupal'))) . "\n";
  $message['body'][] = t('To stop receiving these e-mails, change your notification preferences at !notify-url', array(
    '!notify-url' => url("user/$user->uid/notify", array('absolute' => TRUE)),
  )) . "\n";
}

/**
 * Switch from original user to mail submission user and back.
 *
 * NOTE: Copied from mailhandler
 *
 * Note: You first need to run _notify_switch_user without
 * argument to store the current user. Call _notify_switch_user
 * without argument to set the user back to the original user.
 *
 * @param int $uid
 *   The user ID to switch to.
 */
function _notify_switch_user($uid = NULL) {
  global $user;
  static $orig_user = array();

  if (isset($uid)) {
    // Should a user visit cron.php, or should this module be invoked
    // via poormanscron and _notify_send() does not complete, the
    // visitor will end up logged in as the "switched to user" for
    // subsequent requests unless we disable saving the session
    // until we are sure we're the invoking user again.
    drupal_save_session(FALSE);
    $user = user_load($uid);
  }
  // Retrieve the initial user, can be called multiple times.
  elseif (count($orig_user)) {
    $user = array_shift($orig_user);
    array_unshift($orig_user, $user);
    drupal_save_session(TRUE);
  }
  // Store the initial user.
  else {
    $orig_user[] = $user;
  }
}

/**
 * Helper function that queues any unpublished comments so
 * users can be notified when the comments are published.
 */
function _notify_queue_unpublished_comments() {
  db_query("INSERT INTO {notify_unpublished_comments_queue} (cid, nid)
    SELECT c.cid, c.nid
    FROM {comment} c
    LEFT JOIN {notify_unpublished_comments_queue} q ON q.cid = c.cid
    WHERE c.status = :status AND q.cid IS NULL", array(':status' => COMMENT_NOT_PUBLISHED));
}

/**
 * Implementation of hook_node_delete().
 *
 * Delete any unpublished comments in the queue associated
 * with the node being deleted.
 */
function notify_node_delete($node) {
  db_query('DELETE FROM {notify_unpublished_comments_queue} WHERE nid = :nid', array(':nid' => $node->nid));
}

/**
 * Implementation of hook_comment_insert().
 *
 * Add any newly created unpublished comments to the queue.
 */
function notify_comment_insert($comment) {
  if ($comment->status == COMMENT_NOT_PUBLISHED) {
    db_query('INSERT INTO {notify_unpublished_comments_queue} (cid, nid) VALUES (:cid, :nid)', array(':cid' => $comment->cid, ':nid' => $comment->nid));
  }
}

/**
 * Implementation of hook_comment_delete().
 *
 * Delete the unpublished comment in the queue when the
 * comment itself is deleted.
 */
function notify_comment_delete($comment) {
  db_query('DELETE FROM {notify_unpublished_comments_queue} WHERE cid = :cid', array(':cid' => $comment->cid));
}